SctLib: Change the case of the x64 directory
On case-sensitive file systems the directory name needs to match that of
the architecture otherwise the compiler complains like so,

In file included from /edk2.git/SctPkg/Library/SctLib/Alloc.c:47:0:
/edk2.git/SctPkg/Library/SctLib/SctLibInternal.h:51:24: fatal error: SctLibPlat.h: No such file or directory

Signed-off-by: Matt Fleming <matt.fleming@intel.com>